// app/layout.tsx
import type { Metadata } from "next";
import Script from "next/script";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";



export const metadata: Metadata = {
  title: "SoftCare OPD Portal",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/favicon.png",
    apple: "/assets/img/apple-touch-icon.png",
  },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <div className="flex">
        <Sidebar />
        <main id="main" className="main" style={{ minHeight: "80vh", padding: "20px" }}>
          {children}
        </main>
      </div>
      <Footer />
    </>
  );
}
