// app/layout.tsx
import type { Metadata } from "next";
import Script from "next/script";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";



export const metadata: Metadata = {
  title: "SoftCare OPD Portal",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/favicon.png",
    apple: "/assets/img/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Nunito:300,400,600,700|Poppins:300,400,500,600,700"
          rel="stylesheet"
        />

        {/* Vendor CSS */}
        <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" />
        <link rel="stylesheet" href="/assets/vendor/boxicons/css/boxicons.min.css" />
        <link rel="stylesheet" href="/assets/vendor/quill/quill.snow.css" />
        <link rel="stylesheet" href="/assets/vendor/quill/quill.bubble.css" />
        <link rel="stylesheet" href="/assets/vendor/remixicon/remixicon.css" />
        <link rel="stylesheet" href="/assets/vendor/simple-datatables/style.css" />

        {/* Main CSS */}
        <link rel="stylesheet" href="/assets/css/style.css" />
      </head>

      <body>
         {/* Layout */}
        <Header />
        <div className="flex">
          <Sidebar />
          <main id="main" className="main" style={{ minHeight: "80vh", padding: "20px" }}>
            {children}
          </main>
        </div>
        <Footer />

        {/* Scripts */}

        {/* Vendor JS */}
        <Script
          src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <Script src="/assets/vendor/chart.js/chart.umd.js" strategy="lazyOnload" />
        <Script src="/assets/vendor/echarts/echarts.min.js" strategy="lazyOnload" />
        <Script src="/assets/vendor/quill/quill.js" strategy="lazyOnload" />
        <Script
          src="/assets/vendor/simple-datatables/simple-datatables.js"
          strategy="lazyOnload"
        />
        <Script src="/assets/vendor/tinymce/tinymce.min.js" strategy="lazyOnload" />
        <Script
          src="/assets/vendor/php-email-form/validate.js"
          strategy="lazyOnload"
        />

        {/* Main JS */}
        <Script src="/assets/js/main.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
